version: '3'

services:
  web:
    image: golang:latest
    working_dir: /go/src/github.com/mono0x/puroland-greeting
    command: go run main.go serve --addr=:8080
    volumes:
      - .:/go/src/github.com/mono0x/puroland-greeting
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres:11.1-alpine
    restart: always
    ports:
      - '13306:3306'