version: '3'

services:
  web:
    image: golang:1.11.2
    depends_on:
      - wait_for_dependencies
      - postgres
    working_dir: /go/src/github.com/mono0x/puroland-greeting
    command: go run main.go serve --addr=:8080
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      TZ: Asia/Tokyo
    volumes:
      - .:/go/src/github.com/mono0x/puroland-greeting
    ports:
      - '8080:8080'
    networks:
      - external_network
      - internal_network

  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=ja_JP.UTF-8
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
    - internal_network

  wait_for_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgres
    command: postgres:5432
    networks:
    - internal_network

networks:
  external_network:
  internal_network:
    internal: true
